### ISSUE TITLE
When support AFNetworking3.0

### ISSUE THREAD

**Issue by yangxiaolongYasin** [DyKnow/SignalR-ObjC#271] opened 2016-06-30 08:58 UTC
When support AFNetworking3.0？Can you let scoket support IPv6？

**Comment by ozzotto** [comment] 2016-06-30 09:54
+1

**Comment by Chriztophaa** [comment] 2016-07-12 12:27
Hey,

we would also love to hear, that  AFNetworking 3.x will be supported. 
It seems that the only problem is the SRServerSentEvents which use a special variant for the call.
The other calls in Socket and LongPolling can be easily transfered (we did that, and don't use serversentevents currently!)

If we can support you doing the changes, please let us know!!

**Comment by abillingsley** [comment] 2016-07-19 16:15
@Chriztophaa I've started looking into how AFHTTPSessionManager can be used for ServerSentEvents in my free time.  I have a working prototype but really need to get the unit tests updated before I can reasonably share my changes.

In case you wanted to give an implementation a shot, my approach so far has been to create a subclass for AFHTTPSessionManager that overrides the NSURLSessionDataDelegate method 

``` objectivec
- (void)URLSession:(NSURLSession *)session
          dataTask:(NSURLSessionDataTask *)dataTask
    didReceiveData:(NSData *)data {
    [super URLSession:session dataTask:dataTask didReceiveData:data];
    if (self.urlSessionTaskDidReceiveData) {
        self.urlSessionTaskDidReceiveData(dataTask, data);
    }
}
```

`urlSessionTaskDidReceiveData` above is a block that can be implemented by the transport layer to expose the NSData received by the connection and the transport layer can stringify and parse the data in a similar fashion to how the EventSourceStreamReader works.

P.S. if you do get something working and test coverage to support the changes PRs are always appreciated

**Comment by mouchegmouradian** [comment] 2016-07-21 06:59
@abillingsley Are you planning on making a PR soon or do I need to give it a try ?

**Comment by abillingsley** [comment] 2016-07-23 20:59
@kimimsc I have started my changes on `feature-afnetworking3.x` as it exists this branch still uses afnetworking 2.x but has moved ServerSentEvents to AFHTTPSessionManager/NSURLSession.  At this point the changes are very raw and still require some work to get the remaining transports ready for afnetworking 3.x but those transports _should_ be easier to port

**Comment by mouchegmouradian** [comment] 2016-07-23 22:18
@abillingsley Thanks mate ! I had started to port ServerSentEvents as well. I'll check out what you've done when I find the time. Cheers

**Comment by abillingsley** [comment] 2016-07-28 12:30
duplicate of #233

**Closed as completed by abillingsley** 2016-07-28 12:30 UTC
