### ISSUE TITLE
About  EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ellezerh** [DyKnow/SignalR-ObjC#251] opened 2016-03-15 22:56 UTC
Hi,
We are using signalr websocket technology to stream data from server to ios application and also besides that, developing our ios applicaition by using your signalR/Obj-c framework. 
after 5 minutes our appliation was started, we are getting error "EXC_BAD_ACCESS". 

this error is at 90 line in SREventSourceStreamReader.m

at line 50 :
			NSData *buffer = [stream propertyForKey:NSStreamDataWrittenToMemoryStreamKey];

Could you help us about this issue?

Best Regards,

**Comment by abillingsley** [comment] 2016-03-16 12:13
closing as duplicate of #243

**Closed by abillingsley** 2016-03-16 12:13 UTC
