### ISSUE TITLE
I have two issuesSRLongPollingTransport is not updated with AFNetworking 3.0*

### ISSUE THREAD

**Issue by NarayanaT** [DyKnow/SignalR-ObjC#264] opened 2016-05-13 08:30 UTC
**ISSUE 1**. I have downloaded the source code, and I want use it for my custom iOS App, 
So I have copied the "NetWork" & "SignalR.Client"  folders.
Now I have installed AFNetworking and SocketRocket through Pods.
It seems the AFNetWork is updated to version 3.\* where as the SRLongPollingTransport is not updated.

**ISSUE2:**  I have downloaded the source code, and I want use it for my custom iOS App, 
So I have copied the "NetWork" & "SignalR.Client"  folders.
Now I have installed AFNetworking to 2.6.3 version and SocketRocket through Pods.
I want to develope a library file which including the WebSocket, that means the SignalR code is inside of my library where as the library I have to use in another project.
It's building properly and generating the library (.a) file.

Now, when I add the library in to another new project then it's not compiling, it's throwing some errors saying 
a.   Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:", 

Some times it says armv64, or linker errors 
 b. Undefined symbols for architecture arm64:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in xxxxxxxxxx.a(SRWebSocket.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
## Finally I have blocked in the above two ways. Please help me to build the SocketRocket framework in my library.

Thanks in Advance
Narayana

**Comment by abillingsley** [comment] 2016-05-13 12:45
duplicate of #265

**Closed as completed by abillingsley** 2016-05-13 12:45 UTC
