### ISSUE TITLE
Getting 403 responses errors ONLY when using WebSockets

### ISSUE THREAD

**Issue by rnc505** [DyKnow/SignalR-ObjC#142] opened 2013-07-19 20:25 UTC
I've added SocketRocket to my project and enabled the WebSockets transport, so I have the three transports enabled: "WebSockets", "Server-Sent Events" and "Long Polling". 

However, I always get a 403 error when trying to connect as WebSockets, even though negotiate works fine and tells me to try websockets (And I know for sure websockets work, because my web-javascript client connects via websockets fine). Then it tries SSE and works fine (and I know that Long polling works as well). This is because they use the same AFNetworking instance that takes care of all of the cookies from after logging in.

After searching through SignalR documentation, the 403 is apparently being returned due to a lack of authentication (https://github.com/SignalR/SignalR/blob/ac65ff827291437322fc0eb9650902677425f39c/ReleaseNotes.md#bugs-fixed-7, fixed by error 1308 - https://github.com/SignalR/SignalR/issues/1308), and no where can I set any sort of authentication for sockets, which is a major problem.

**Comment by abillingsley** [comment] 2016-02-05 16:33
duplicate of #231

**Closed by abillingsley** 2016-02-05 16:33 UTC
