### ISSUE TITLE
SRConnectionDidReconnect:(id <SRConnectionInterface>)connection event doesn't get called in background

### ISSUE THREAD

**Issue by yesnoyes** [DyKnow/SignalR-ObjC#182] opened 2014-11-25 09:49 UTC
When app goes to background, connection to socket is closed after few seconds but when it comes to foreground again 

- (void)SRConnectionDidReconnect:(id <SRConnectionInterface>)connection

never gets called.

**Comment by abillingsley** [comment] 2016-02-05 16:14
duplicate of #147

**Closed by abillingsley** 2016-02-05 16:14 UTC
Labels: feature
