### ISSUE TITLE
SignalR-Objc requires AFNetworking (~> 2.0) and do not allows to update AFNetworking to 3.1.0

### ISSUE THREAD

**Issue by nabeelarif** [DyKnow/SignalR-ObjC#257] opened 2016-04-04 12:29 UTC
I am unable to update to latest version of AFNetworking i.e 3.1.0 because SignalR-Objc requires (~> 2.0)

```
$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AFNetworking (= 3.1.0)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `SignalR-ObjC/Core (2.0.1)`
```

**Comment by flotteur** [comment] 2016-04-04 15:39
I think this is a duplicate of #233

**Comment by abillingsley** [comment] 2016-04-04 20:17
This is a duplicate of #233 SignalR-ObjC does not yet support AFNetworking 3.x

**Closed as completed by abillingsley** 2016-04-04 20:17 UTC

**Comment by thesaad** [comment] 2016-07-28 12:14
Hey Folks: Found solution to this. Please see answer by "Saad" for this question on [Stackoverflow](http://stackoverflow.com/questions/28592045/cocoapods-afnetworking-required-by-podfile/38635770#38635770). But you will be required to edit code of SignalR by using Xcode. That is to replace all old AFHTTPRequestOperation to latest AFNetworking 3.0 according to the [AFNetowrking 3.0 Migration Guid](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide)
