### ISSUE TITLE
Groups not working on IOS while no issue in .Net Client

### ISSUE THREAD

**Issue by izhar-ap** [DyKnow/SignalR-ObjC#176] opened 2014-10-02 07:29 UTC
I am unable to send messages to IOS Devices via
 Clients.Group("FOO").Send(objmsg) 
while everything works perfectly when using
Clients.All.Send(objmsg)
I have to create custom groups using a Dictionary
public static Dictionary< string, List< string >> CustomGroups;
Note: On .Net Client Groups works prefectly

**Comment by abillingsley** [comment] 2015-08-17 12:47
duplicate of #184

**Closed by abillingsley** 2015-08-17 12:47 UTC
